# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNDemoApp

  target 'RNDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNDemoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNDemoApp-tvOS

  target 'RNDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
