# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNDemoApp

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'RNDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNDemoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNDemoApp-tvOS

  target 'RNDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
